### PR TITLE
code changes for GetByParentID to generate storeproc with parent column query

### PR DESCRIPTION
**Pull request by vamsigollamudi**

### CODE REVIEW

**Review by SergeyBarskiy — CHANGES_REQUESTED** [review]
Could you please update readme file with the new type of procedure please?
Thanks.

**Comment by vamsigollamudi** [comment]
Updated the same...

**Comment by SergeyBarskiy** [comment]
There is an issue with the code.  For example, if I run
-s . -d ContactManager -t Company -k getbyparentid -pc City
The procedure looks as 
CREATE PROCEDURE [dbo].[usp_Company_GetByParentId]
(
	@CompanyId INT
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[CompanyId],
	[City],
	[CompanyName],
	[State],
	[Street],
	[Zip],
	[RowVersionNumber]
FROM [dbo].[Company]
WHERE
	[City] = @City  

END
This means that the parameter is not correct, it does not math the Where

**Review by SergeyBarskiy — CHANGES_REQUESTED** [review]
There is an issue with the code. For example, if I run
-s . -d ContactManager -t Company -k getbyparentid -pc City
The procedure looks as
CREATE PROCEDURE [dbo].[usp_Company_GetByParentId]
(
@CompanyId INT
)
AS
BEGIN
SET NOCOUNT ON;
SELECT
[CompanyId],
[City],
[CompanyName],
[State],
[Street],
[Zip],
[RowVersionNumber]
FROM [dbo].[Company]
WHERE
[City] = @city

END
This means that the parameter is not correct, it does not match the Where clause

**Review by SergeyBarskiy — COMMENTED** [review]
Looks good.  Thanks.

**Review by SergeyBarskiy — APPROVED** [review]
Done

**Pull request merged**
